if (self.CavalryLogger) { CavalryLogger.start_js(["BAs6o"]); }

__d("BusinessActorUtils.brands",["UnicodeCJK"],(function(a,b,c,d,e,f){"use strict";a={getInitials:function(a,c){a===void 0&&(a="");c===void 0&&(c="");a=a.trim().charAt(0);c=c.trim().charAt(0);a=a+c;return b("UnicodeCJK").hasIdeograph(a)?c:a.toUpperCase()}};e.exports=a}),null);
__d("UFIAsyncWrapper",["React"],(function(a,b,c,d,e,f){"use strict";e.exports=b("React").Fragment}),null);
__d("UFIDispatcher",["ReactDispatcher_DEPRECATED","UFISharedDispatcher"],(function(a,b,c,d,e,f){"use strict";__p&&__p();a=function(a){babelHelpers.inheritsLoose(c,a);function c(){return a.apply(this,arguments)||this}var d=c.prototype;d.dispatch=function(c){a.prototype.dispatch.call(this,c),b("UFISharedDispatcher").dispatch(c)};return c}(b("ReactDispatcher_DEPRECATED"));e.exports=a}),null);
__d("UFINewCommentNotifier",["Arbiter","UFIFeedbackTargets","UFIUserActions"],(function(a,b,c,d,e,f){"use strict";a={onNewComment:function(a,c,d,e,f,g){b("UFIUserActions").addComment(c.ftentidentifier,d.visibleValue,d.encodedValue,{source:c.source,ufiinstanceid:c.instanceid,target:e,replyid:f,rootid:c.rootid,attachedphoto:d.attachedPhoto,attachedvideo:d.attachedVideo,attachedfile:d.attachedFile,attachedsticker:d.attachedSticker,feedcontext:c.feedcontext,timestamp:g,feedbackReferrer:c.feedbackReferrer,isMarkdown:d.isMarkdown,fluentContentToken:c.fluentContentToken,isActiveLivingRoom:c.isActiveLivingRoom,livingRoomID:c.livingRoomID,isLiveVOD:c.isLiveVOD,islivestreaming:c.islivestreaming,liveVideoQuickCommentQuality:d.liveVideoQuickCommentQuality,photoTextTagID:c.photoTextTagID,isPhotoTag:c.isPhotoTag,photoFBID:c.photoFBID,photoTagX:c.photoTagX,photoTagY:c.photoTagY,privacyValue:d.privacy_value,section:d.section,selectedInsightPoint:d.selectedInsightPoint,attachedshareurl:d.attachedShareURL,isBroadcasterUFI:c.isBroadcasterUFI,enableVODCommentTimestamps:c.enableVODCommentTimestamps,trackingID:d.trackingID,delightRanges:d.delightRanges}),b("UFIFeedbackTargets").getFeedbackTarget(c.ftentidentifier,function(f){a&&b("Arbiter").inform("ufi/comment",{ft_id:f.entidentifier,target:e,form:a,isinverted:f.isranked||c.islivestreaming||c.isActiveLivingRoom,isPhotoTag:c.isPhotoTag,photoTextTagID:c.photoTextTagID,photoTagX:c.photoTagX,photoTagY:c.photoTagY,commentString:d.visibleValue})})}};e.exports=a}),null);
__d("UFICallbackStore",["FluxStore"],(function(a,b,c,d,e,f){"use strict";__p&&__p();a=function(a){__p&&__p();babelHelpers.inheritsLoose(b,a);function b(){return a.apply(this,arguments)||this}var c=b.prototype;c.__onDispatch=function(a){var b=a.type;a=babelHelpers.objectWithoutPropertiesLoose(a,["type"]);this.__emitter.emit(b,a)};c.on=function(a,b){return this.__emitter.addListener(a,b)};c.remove=function(){this.__emitter.removeAllListeners()};return b}(b("FluxStore"));a.__moduleID=e.id;e.exports=a}),null);
__d("UFIBusinessActorIcon.react",["cx","AppUserRoleConstants.brands","BusinessActorUtils.brands","React","getObjectValues","joinClasses","prop-types"],(function(a,b,c,d,e,f,g){"use strict";__p&&__p();a=function(a){babelHelpers.inheritsLoose(c,a);function c(){return a.apply(this,arguments)||this}var d=c.prototype;d.render=function(){var a=b("BusinessActorUtils.brands").getInitials(this.props.firstName,this.props.lastName),c=this.props.businessRole===b("AppUserRoleConstants.brands").ADMIN;return b("React").jsx("div",{className:b("joinClasses")(this.props.classNames,"_1rpl"),children:b("React").jsx("div",{align:"center",className:b("joinClasses")(this.props.textClassNames,c?"_1rpm":null),children:a})})};return c}(b("React").Component);a.propTypes={firstName:(c=b("prop-types")).string.isRequired,lastName:c.string.isRequired,classNames:c.string,textClassNames:c.string,businessRole:c.oneOf(b("getObjectValues")(b("AppUserRoleConstants.brands")))};e.exports=a}),null);
__d("UFIActorIconContainer.react",["cx","ClickableArea.react","Image.react","JSResource","React","ShortProfiles","UFIBusinessActorIcon.react","XUISpinner.react","joinClasses","lazyLoadComponent"],(function(a,b,c,d,e,f,g){"use strict";__p&&__p();var h=b("lazyLoadComponent")(b("JSResource")("UFIActorSelector.react").__setRef("UFIActorIconContainer.react")),i=b("React").jsx(b("XUISpinner.react"),{size:"large"});a=function(a){__p&&__p();babelHelpers.inheritsLoose(c,a);function c(){var b,c;for(var d=arguments.length,e=new Array(d),f=0;f<d;f++)e[f]=arguments[f];return(b=c=a.call.apply(a,[this].concat(e))||this,c.state={actor:null,showActorSelectorDialog:!1},c.$2=function(){c.setState(function(a){return{showActorSelectorDialog:!a.showActorSelectorDialog}})},b)||babelHelpers.assertThisInitialized(c)}var d=c.prototype;d.componentDidMount=function(){this.$1(this.props.actorID)};d.componentDidUpdate=function(a){this.props.actorID!==a.actorID&&this.$1(this.props.actorID)};d.$1=function(a){var c=this;b("ShortProfiles").get(a,function(a){return c.setState({actor:a})})};d.render=function(){__p&&__p();var a=this.state.actor;if(!a)return this.props.tinyIcon?b("React").jsx(b("XUISpinner.react"),{size:"small"}):i;var c;this.props.tinyIcon?c=b("joinClasses")("img UFIActorImage _3tm9",this.props.className):this.props.smallIcon?c=b("joinClasses")("img UFIActorImage _3qxe",this.props.className):c=b("joinClasses")("img UFIActorImage _54ru",this.props.className);var d=this.props.actorSelectorConfig!=null&&this.props.isLivingRoom&&this.props.overlayActorSelectorOnUFIPhoto===!0;d&&(c=b("joinClasses")("UFIActorImageWithSelector",c));d=a.isBusinessPersona?b("React").jsx(b("UFIBusinessActorIcon.react"),{classNames:c,firstName:a.firstName,lastName:a.lastName,textClassNames:"UFIBusinessActorIconText"}):b("React").jsx(b("Image.react"),{alt:a.name,className:c,src:a.thumbSrc});if(this.props.actorSelectorConfig!=null&&this.props.isLivingRoom&&this.props.overlayActorSelectorOnUFIPhoto===!0){return(c=b("React")).jsxs("div",{className:"UFIActorImageContainer",children:[c.jsx(b("ClickableArea.react"),{onClick:this.$2,children:c.jsx("div",{className:"UFIActorSelectorOverlay"})}),c.jsx(c.Suspense,{fallback:c.jsx("div",{}),children:c.jsx(h,babelHelpers["extends"]({},this.props.actorSelectorConfig.props,{dialogShown:this.state.showActorSelectorDialog,useUFIPhotoOverlay:!0,onActorChange:this.props.onActorChange}))}),d]})}return d};return c}(b("React").Component);e.exports=a}),null);
__d("UFIDispatcherContext.react",["React","prop-types"],(function(a,b,c,d,e,f){"use strict";__p&&__p();a=function(a){babelHelpers.inheritsLoose(b,a);function b(){return a.apply(this,arguments)||this}var c=b.prototype;c.getChildContext=function(){return{dispatch:this.props.dispatcher.dispatch.bind(this.props.dispatcher),stores:this.props.stores}};c.render=function(){return this.props.children};return b}(b("React").Component);a.childContextTypes={dispatch:b("prop-types").func,stores:b("prop-types").object};e.exports=a}),null);
__d("IntlLang",["UnicodeBidi"],(function(a,b,c,d,e,f){"use strict";__p&&__p();c={HE:"\u0590\u05be\u05c0\u05c3\u05c6\u05c8-\u05cf\u05d0-\u05ea\u05eb-\u05ef\u05f0-\u05f2\u05f3-\u05f4\u05f5-\u05ff\u07c0-\u07c9\u07ca-\u07ea\u07f4-\u07f5\u07fa\u07fb-\u07ff\u0800-\u0815\u081a\u0824\u0828\u082e-\u082f\u0830-\u083e\u083f\u0840-\u0858\u085c-\u085d\u085e\u085f-\u089f\u200f\ufb1d\ufb1f-\ufb28\ufb2a-\ufb36\ufb37\ufb38-\ufb3c\ufb3d\ufb3e\ufb3f\ufb40-\ufb41\ufb42\ufb43-\ufb44\ufb45\ufb46-\ufb4f"};var g=new RegExp("["+c.HE+"]");function a(a){a=b("UnicodeBidi").firstStrongChar(a);if(a==null)return null;return g.exec(a)?"he":null}d={getLang:a};e.exports=d}),null);
__d("XAnimatedImageInLiveCommentPreviewController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/gifs/in_live_comment/",{})}),null);
__d("XChatCommandResultCommentPreviewController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/chat_command_result/live_comment_attachment/",{})}),null);
__d("XDonationCommentPreviewController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/fundraiser_for_story/live_comment_attachment/",{})}),null);
__d("XFileCommentPreviewController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/files_in_comments/live_comment_attachment/",{})}),null);
__d("XMarketplaceEcommProductItemCommentPreviewController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/marketplace_comments/ecomm_product_item_attachment/",{})}),null);
__d("XTipJarCommentPreviewController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/tip_jar/live_comment_attachment/",{})}),null);
__d("XUFIEditCommentNuxController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/ufi/comment/edit/nux/",{})}),null);
__d("XUFISubscribeCommentController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/ufi/comment/subscribe/",{})}),null);
__d("XVideoBroadcastClearPinCommentEventAsyncController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/videos/pinnedcomments/clear/",{})}),null);
__d("XVideoBroadcastPinnedCommentsController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/videos/pinnedcomments/",{})}),null);
__d("XVideoInLiveCommentPreviewController",["XController"],(function(a,b,c,d,e,f){e.exports=b("XController").create("/video/in_live_comment/",{})}),null);